stages:
  one_stage_pipeline:
    cmd: papermill notebooks/model_exp.ipynb notebooks/model_exp_out.ipynb
    deps:
    - notebooks/X_test_scaled.csv
    - notebooks/X_train_scaled.csv
    - notebooks/model_exp.ipynb
    - notebooks/y_test.csv
    - notebooks/y_train.csv
    params:
    - base
    - train
    outs:
    - notebooks/model.joblib
    metrics:
    - notebooks/metrics.json:
        cache: false